### ISSUE TITLE
Installation Procedure

### ISSUE THREAD

**Issue by alexalburca** [aytuncbeken/zabbix-monitor-gitlab#1]
But I was confused as is the installation of scripts.

Do I need ansible on zabbix server? and run the ansible-playbook command -i hosts playbooks / install.yml on zabbix server?

Or is the whole installation done on the zabbix agent's own server, which is the same as gitlab?

**Comment by aytuncbeken** [comment]
Hi Alex,

You install Ansible and run playbook on any host which have connection to server which Zabbix Agent is already installed. 

Thanks
